### ISSUE TITLE
Unable to parse expression strings that have multiple #

### ISSUE THREAD

**Issue by jobanputra** [ncalc/ncalc-async#6]
When the expression contains multiple `#` characters, the `Expression` constructor throws the following exception: `"String '' was not recognized as a valid DateTime."`

For example the expression that I am trying to parse is
```
Format("{0:(###) ###-####}", "9999999999")
```

Update: I understand that NCalc uses sharps (#) to delimit date. However # is a [custom string specifier in the .NET framework](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#SpecifierD).

**Comment by petli** [comment]
Try this instead:

    Format('{0:(###) ###-####}', '9999999999')

The NCalc expression syntax uses `'` instead of `"` to represent strings (see https://github.com/ncalc/ncalc/wiki/Values).

You should've gotten a syntax error from the `"` rather than it continuing to the `#`, though. I think it looks like the lexer is configured to recover rather than immediately throwing an error, I'll look further into that.

**Comment by petli** [comment]
Fix for the missing syntax error exception is included in this version: https://www.nuget.org/packages/NCalcAsync/2.1.5

**Comment by petli** [comment]
Thanks for reporting this! It was a pretty deep bug in the expresison parser which have probably frustrated others over the years NCalc have existed.
